### ISSUE TITLE
Allow creatures to eat food in the environment.

### ISSUE THREAD

**Issue by 8Mobius8** [LifeQuestions/survival#6]
Allow creatures to eat food in the environment. When food is eaten it should be removed from the environment.
(Should eating be a all at once action or take multiple turns based on food size?)

**Comment by 8Mobius8** [comment]
I would say let's start with just it just taking one action to each food, and all locations with food have the same size.

That said, let's make the food size `float` or `int` so we can change the food sizes in each location later.

**Comment by aswizzl** [comment]
sounds good, so are you doing this? i'm confused by this system lol

**Comment by aswizzl** [comment]
Eating should increase HP by X amount. HP decreases by 1 every turn to simulate hunger.
